version = 0.1

[default.deploy.parameters]
stack_name = "tuneout-music"
resolve_s3 = true                  # does not create new bucket
s3_bucket = "wits-sam-deployments"
s3_prefix = "tuneout-music"
region = "us-east-1"
confirm_changeset = true            # asks for permission once shows you what's going to change
capabilities = "CAPABILITY_IAM"     # has ability to manipulate permissions (policies)
disable_rollback = true             # if deployment fails doesn't rollback (stays in failed state so you can check what went wrong)
image_repositories = []
